services:
    minio:
        image: quay.io/minio/minio:latest
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: 'rootroot'
            MINIO_ROOT_PASSWORD: 'rootroot'
        volumes:
            - minioData:/data
        healthcheck:
            test: ['CMD', 'mc', 'ready', 'local']
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - app
        ports:
            - 9000:9000
            - 9001:9001
    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'express-articles'
        volumes:
            - database:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/local/bin/healthcheck.sh',
                    '--su-mysql',
                    '--connect',
                    '--innodb_initialized',
                ]
            interval: 5s
            timeout: 30s
            retries: 5
        networks:
            - app
        ports:
            - 3309:3306

volumes:
    database:
    minioData:

networks:
    app:
